export const CHESS_CONFIG = {
  BOARD_SIZE: 'w-full max-w-[90vw] sm:max-w-[70vw] md:max-w-[60vw] lg:max-w-[480px]',
  PIECE_SIZE: 'text-2xl sm:text-3xl md:text-4xl',
  SQUARE_SIZE: 'aspect-square relative',
  WHITE_PIECE_COLOR: 'text-white',
  BLACK_PIECE_COLOR: 'text-blue-600',
  BLACK_PAWN_COLOR: 'text-blue-600',
  WHITE_PAWN_COLOR: 'text-white',
  WHITE_ROOK_COLOR: 'text-white',
  WHITE_KNIGHT_COLOR: 'text-white',
  WHITE_BISHOP_COLOR: 'text-white',
  WHITE_QUEEN_COLOR: 'text-white',
  WHITE_KING_COLOR: 'text-white',
  BLACK_ROOK_COLOR: 'text-blue-600',
  BLACK_KNIGHT_COLOR: 'text-blue-600',
  BLACK_BISHOP_COLOR: 'text-blue-600',
  BLACK_QUEEN_COLOR: 'text-blue-600',
  BLACK_KING_COLOR: 'text-blue-600',
};
